busGal_Django/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('buses.urls')),
    path('xenovaping/', include('xenovaping.urls'))
]

buses/urls.py
from django.urls import path

from . import views

app_name = 'buses'
urlpatterns = [
    path('', views.trip_search, name='trip_search'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
    path('results/<int:origin_id>/<str:origin_type>/<str:origin_name>/<int:destination_id>/<str:destination_type>/<str:destination_name>/<int:timestamp>',
         views.results, name='results'),  # Date is a UNIX timestamp
    path('results/<int:origin_id>/<str:origin_type>/<str:origin_name>/<int:destination_id>/<str:destination_type>/<str:destination_name>',
         views.results, name='results'),  # Without date (is optional)
    path('monitor_stop_form', views.monitor_stop_form, name='monitor_stop_form'),
    path('monitor_stop/<int:stop_id>', views.monitor_stop, name='monitor_stop'),
]

buses/forms.py
from django import forms

import busGal_api as busapi
import datetime


class StopSearchForm(forms.Form):
    stop = forms.ChoiceField(required=True, label='Stop', widget=forms.Select(
        attrs={'class': 'select2', 'data-placeholder': 'Start typing to search'}))


class TripSearchForm(forms.Form):
    origin = forms.ChoiceField(required=True, label='Origin', widget=forms.Select(
        attrs={'class': 'select2', 'data-placeholder': 'Start typing to search'}))

    destination = forms.ChoiceField(required=True, label='Destination', widget=forms.Select(
        attrs={'class': 'select2', 'data-placeholder': 'Start typing to search'}))

    def get_current_date_formatted():
        return datetime.date.today().strftime("%Y-%m-%d")

    date = forms.DateField(required=True, label='Date', initial=datetime.date.today, widget=forms.DateInput(attrs={
                           'class': 'bg-white text-black', 'type': 'date', 'min': get_current_date_formatted}))  # type=date for the bootstrap+system datepicker to appear

buses/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from .forms import TripSearchForm, StopSearchForm
from .templatetags.buses_extras import form_stop_string as _create_form_stop_string

from .utils.stops_cache import stops_cache

from busGal_api import transport as busapi
from datetime import date, datetime
import time


def _parse_form_stop_string(string: str) -> busapi.stops.Stop:
    return busapi.stops.Stop(*string.split("/", 2))


def trip_search(request):
    if request.method == 'POST':
        form = TripSearchForm(request.POST)

        # To make the form valid
        origin_id = request.POST.get("origin")
        destination_id = request.POST.get("destination")
        form.fields['origin'].choices = [(origin_id, origin_id)]
        form.fields['destination'].choices = [(destination_id, destination_id)]

        if form.is_valid():
            origin = _parse_form_stop_string(form.cleaned_data['origin'])
            destination = _parse_form_stop_string(
                form.cleaned_data['destination'])

            timestamp = int(time.mktime(form.cleaned_data['date'].timetuple()))

            return redirect('buses:results', origin.id, origin.type, origin.name, destination.id, destination.type, destination.name, timestamp)
    else:
        form = TripSearchForm()

        origin = request.GET.get("origin")  # form_stop_string
        destination = request.GET.get("destination")  # form_stop_string
        if origin:
            form.fields['origin'].choices = [
                (origin, _parse_form_stop_string(origin).name)]
            form.fields['origin'].initial = origin
        if destination:
            form.fields['destination'].choices = [
                (destination, _parse_form_stop_string(destination).name)]
            form.fields['destination'].initial = destination

    return render(request, 'buses/searchform.html', {'form_header': 'Prepare your trip', 'form': form})


def monitor_stop(request, stop_id):
    trip_date = datetime.now()

    queried_stop, expeditions = busapi.expeditions.get_expeditions_from_stop(
        stop_id, datetime.now(), real_time=True)

    return render(request, 'buses/stop_monitoring.html', {'stop': expeditions[0].passing_stop if expeditions else queried_stop,
                                                          'date': trip_date,
                                                          'expeditions': expeditions})


def monitor_stop_form(request):
    if request.method == 'POST':
        form = StopSearchForm(request.POST)

        # To make the form valid
        stop_id = request.POST.get("stop")
        form.fields['stop'].choices = [(stop_id, stop_id)]

        if form.is_valid():
            stop = _parse_form_stop_string(form.cleaned_data['stop'])

            return redirect('buses:monitor_stop', stop.id)
    else:
        form = StopSearchForm()

    return render(request, 'buses/searchform.html', {'form_header': 'Search a stop to see real-time information', 'form': form})


def autocomplete(request):
    query = request.GET.get("q")

    if query is None:
        options = []
    else:
        options = stops_cache.autocomplete_search(query)

    return JsonResponse({"results": options})


def results(request, origin_id, origin_type, origin_name, destination_id, destination_type, destination_name, timestamp=int(time.mktime(date.today().timetuple()))):  # Date is a UNIX timestamp
    origin = busapi.stops.Stop(
        id=origin_id,
        type=origin_type,
        name=origin_name)
    destination = busapi.stops.Stop(
        id=destination_id,
        type=destination_type,
        name=destination_name)

    trip_date = date.fromtimestamp(timestamp)

    expeditions = busapi.expeditions.search_expeditions(
        origin, destination, trip_date)

    return render(request, 'buses/results.html', {'origin': origin,
                                                  'destination': destination,
                                                  'date': trip_date,
                                                  'timestamp': timestamp,
                                                  'expeditions': expeditions})

buses/templates/buses/results.html
{% extends 'main/base.html' %}
{% block content %}
{% if expeditions %}
{% load buses_extras %}
<div class="row mb-3 mt-2">
    <h1 class="text-center"><b>{{ origin.name }} <a class="btn btn-outline-primary btn-lg"
                style="text-decoration: none;"
                href="{% url 'buses:results' destination.id destination.type destination.name origin.id origin.type origin.name timestamp %}">↔️</a>
            {{ destination.name }}</b>
        🗓️ {{ date|date:'d/m/Y' }}</h1>
</div>
<div class="row mb-3">
    <table class="table table-striped">
        <tr>
            <th scope="col">Origin</th>
            <th scope="col">Departure</th>
            <th scope="col">Destination</th>
            <th scope="col">Arrival</th>
            <th scope="col">More information</th>
        </tr>
        {% for expedition in expeditions %}
        <tr>
            <td>
                {{ expedition.origin|stop_button }}
            </td>
            <td>{{ expedition.origin.time|date:'H:i' }}</td>
            <td>{{ expedition.destination|stop_button }}
            </td>
            <td>{{ expedition.destination.time|date:'H:i' }}</td>
            <td><b>{{ expedition.code }}</b> - <a href="{{ expedition.bus_dot_gal_url }}">{{ expedition.line.name }}</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<div class="row mb-3 mt-2">
    <h1 class="text-center"><b>No expeditions are available</b> 😭</h1>
</div>
{% endif %}
{% endblock %}

buses/templates/buses/searchform.html
{% extends 'main/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link href="{% static 'buses/css/searchform.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container justify-content-center my-5">
    <h1 class="text-center">{{ form_header }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Search" extra_classes="w-100 mt-3" %}
    </form>
</div>

<script>
    $(document).ready(function () {
        $(".select2").select2({
            theme: "bootstrap-5",
            width: '100%',
            ajax: {
                url: "{% url 'buses:autocomplete' %}",
                dataType: "json"
            },
            closeOnSelect: false
        });
    });
</script>
{% endblock %}

buses/templates/buses/stop_monitoring.html
{% extends 'main/base.html' %}
{% block content %}
{% if expeditions %}
<div class="row mb-3 mt-2">
    <h1 class="text-center">Buses from <b>{{ stop.name }}</b> 🗓️ {{ date|date:'d/m/Y 🕙 H:i' }}</h1>
</div>
<div class="row mb-3">
    <h5 class="text-center">
        <span class="badge bg-secondary">Not in realtime</span>
        <span class="badge bg-primary">At stop</span>
        <span class="badge bg-danger">Behind schedule</span>
        <span class="badge bg-warning text-dark">Ahead of schedule</span>
        <span class="badge bg-light text-dark">On schedule</span>
    </h5>
</div>
<div class="row mb-3">
    <table class="table table-light table-hover">
        <tr>
            <th scope="col">Line</th>
            <th scope="col">Plate</th>
            <th scope="col">Arrival</th>
            <th scope="col">Distance</th>
            <th scope="col">Delay</th>
        </tr>
        {% for expedition in expeditions %}
        <tr class="{% if not expedition.real_time_data %} table-secondary
        {% elif expedition.real_time_data.MonitoredCall.DistanceFromStop == '0 m' %} table-primary 
        {% elif expedition.real_time_data.Delay|slice:':1' == '-' %} table-warning 
        {% elif expedition.real_time_data.Delay|slice:':3' != 'PT0' %} table-danger {% endif %}">
            <td><a href="{{ expedition.bus_dot_gal_url }}">{{ expedition.line.name }}</a></td>
            <td>{{ expedition.real_time_data.VehicleRef|default:"N/A" }}</td>
            <td>{% if expedition.real_time_data %}
                {% if expedition.real_time_data.MonitoredCall.DistanceFromStop == "0 m" %}
                <b>At stop</b>
                {% else %}
                {{ expedition.real_time_data.MonitoredCall.ExpectedArrivalTime|slice:'-14:-6' }}
                {% endif %}
                {% else %}
                {{ expedition.passing_time|date:'H:i:s' }}
                {% endif %}
            </td>
            <td>{{ expedition.real_time_data.MonitoredCall.DistanceFromStop|default:"N/A" }}</td>
            <td>{{ expedition.real_time_data.Delay|default:"N/A" }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<script>
    $(document).ready(function () {
        const refreshInterval = 30000; // 5 seconds

        // Function to reload the page
        function autoReload() {
            setTimeout(function () {
                location.reload(); // Reload the current page
            }, refreshInterval);
        }

        // Call the autoReload function when the page loads
        autoReload();
    });
</script>
{% else %}
<div class="row mb-3 mt-2">
    <h1 class="text-center"><b>No expeditions are available</b> 😭</h1>
</div>
{% endif %}
{% endblock %}